name: Android CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          gradle-version: '8.4'
          cache-stores: 'build-gradle'
          cache-read-only: false

      - name: Upload debug apk
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
